FROM node:18-alpine3.17

WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm install -g serve

RUN npm install

COPY . .

RUN npm run build

CMD [ "serve", "-s", "build", "-l", "3000" ]